apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
# These are deployment resource labels.  
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: yeguru/backend:{{ .Values.deployment.version }}
        envFrom:
        - configMapRef:
            name: backend  